config/routes.rb
Rails.application.routes.draw do
  get 'user_instruments/index'
  devise_for :users
  root to: "instruments#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :instruments do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[show edit update index destroy]
  resources :user_instruments, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instrument

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
  validates :status, presence: true
  validate :end_date_after_start_date
  validates :instrument, presence: true

  after_create :set_instrument_availability_no
  after_destroy :set_instrument_availability_yes

  def end_date_after_start_date
    if end_date.present? && start_date.present? && end_date <= start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def total_days
    return 0 unless start_date && end_date

    (end_date - start_date).to_i
  end

  def total_price
    return 0 unless instrument

    total_days * instrument.price
  end

  private

  def dates_are_available
    unless instrument.available?(start_date, end_date)
      errors.add(:base, "Instrument is not available for the selected dates")
    end
  end

  def set_instrument_availability_no
    instrument.update(availability: "No")
  end

  def set_instrument_availability_yes
    instrument.update(availability: "Yes")
  end
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  belongs_to :user
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :title, :body ],
  associated_against: {
    user: [ :first_name, :last_name ]
  },
  using: {
    tsearch: { prefix: true }
  }

  # accepts_nested_attributes_for :photos, allow_destroy: true
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 15 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :category, presence: true
  validates :location, presence: true
  validates :availability, presence: true
  validates :user, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def available?(start_date, end_date)
    bookings.where("start_date < ? AND end_date > ?", end_date, start_date).none?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :instruments, dependent: :destroy
  has_many :bookings, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def show
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @booking = Booking.new
    @instrument = Instrument.find(params[:instrument_id])
  end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)
    @instrument = Instrument.find(params[:instrument_id])
    @booking.instrument = @instrument
    @booking.user = current_user
    @booking.status = "Pending"

    if @booking.save!
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'

    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: 'Booking was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: 'Booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :instrument_id)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    if params[:query].present?
      @instruments = Instrument.global_search(params[:query])
    else
      @instruments = Instrument.all
    end
  end

  def show
    @markers =
      [{
        lat: @instrument.latitude,
        lng: @instrument.longitude,
        info_Window: render_to_string(partial: "info_window", locals: { instrument: @instrument }),
        marker_html: render_to_string(partial: "marker")
      }]
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user
    @instrument.save!
    if @instrument.save
      flash[:notice] = "Instrument was successfully created."
      redirect_to instrument_path(@instrument), notice: 'Your Instrument was successfully created.'
    else
      flash[:alert] = @instrument.errors.full_messages.join(', ')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    params[:instrument].delete(:photos) if params[:instrument][:photos] == ['']

    if @instrument.update(instrument_params)
      redirect_to instrument_path(@instrument), notice: 'Your instrument was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @instrument.destroy
    redirect_to instruments_path, notice: 'Your instrument was successfully destroyed.'
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def correct_user
    redirect_to instruments_path, alert: 'Not authorized to delete this instrument.' unless @instrument.user == current_user
  end

  def instrument_params
    params.require(:instrument).permit(:title, :body, :price, :location, :category, :availability, :start_date, :end_date, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/user_instruments_controller.rb
class UserInstrumentsController < ApplicationController
  def index
    @instruments = current_user.instruments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def images_tag(array_of_images, options = {})
    images = []
    if array_of_images.is_a? Array
      array_of_images.each do |image|
        images << images_tag(image, size: options[:size], class: options[:class])
      end
    end
    content_tag :div, images.join("\n").html_safe, class: "img-circle"
  end
end

app/views/bookings/edit.html.erb
<div class="container mt-5">
  <h1>Edit Booking</h1>
  <div class="mt-2">
      <%= simple_form_for @booking do |f| %>
        <%= f.input :start_date, as: :string, input_html: { id: 'start_date' } %>
        <%= f.input :end_date, as: :string, input_html: { id: 'end_date' } %>
        <%= f.button :submit %>
      <% end %>
    </div>
        <%= link_to 'Back', bookings_path, class: "btn btn-secondary" %>
        <%= link_to 'Delete', booking_path(@booking),data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
</div>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

  <div class="container mt-5">
      <div class="row row-cols-3 gy-2">
        <% @bookings.each do |booking| %>
          <div class="col col-md-6 col-lg-4 col-xl-3 mb-4 col-sm-12 col-xs-12">
            <div class="card border border-warning rounded-5 border-1 p-3">
            <p><strong>Start Date:</strong> <%= booking.start_date %></p>
            <p><strong>End Date:</strong> <%= booking.end_date %></p>
            <p><strong>Instrument: </strong> <%= booking.instrument.title %></p>
            <p><strong>Total Price: </strong> <%= booking.total_price  %> <i class="fa-solid fa-euro-sign"></i></p>

            <div style="width: 250px; height: 250px;">
              <% if booking.instrument.photos.attached? %>
                <div id="carousel-<%= booking.id %>" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-indicators">
                    <% booking.instrument.photos.each_with_index do |photo, index| %>
                      <button type="button" data-bs-target="#carousel-<%= booking.id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>" aria-current="<%= 'true' if index == 0 %>" aria-label="Slide <%= index + 1 %>"></button>
                    <% end %>
                  </div>
                  <div class="carousel-inner">
                    <% booking.instrument.photos.each_with_index do |photo, index| %>
                      <div class="carousel-item <%= 'active' if index == 0 %>">
                        <%= image_tag url_for(photo), class: "d-block w-100 align-center", id:"image-book-index" %>
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= booking.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= booking.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
              <% else %>
                <p>No photos available for this instrument.</p>
              <% end %>
            </div>
              <div class="bouton">
                <%= link_to "See Booking", booking_path(booking), class: "bouton"%>
              </div>
            </div>
            </div>
        <% end %>
          </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Book <%= @instrument.title %></h1>

<%= simple_form_for [@instrument, @booking], html: { data: { controller: :datepicker, datepicker_min_date_value: @instrument.start_date, datepicker_max_date_value: @instrument.end_date } } do |f| %>
  <%= f.input :start_date, as: :string, input_html: { data: { datepicker_target: "startDate" } } %>
  <%= f.input :end_date, as: :string, input_html: { data: { datepicker_target: "endDate" } } %>
  <%= f.button :submit, class:"bouton" %>
<% end %>

<% if @booking.start_date && @booking.end_date %>
  <% total_price = (@booking.end_date - @booking.start_date).to_i * @instrument.price_per_day %>
  <span>Total Price:<%= total_price %></span>
<% end %>

app/views/bookings/show.html.erb
<h1 class="my-5">This booking</h1>
<div class="division">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p><strong>Instrument:</strong> <%= @booking.instrument.title %></p>
        <p><strong>Start Date:</strong> <%= @booking.start_date %></p>
        <p><strong>End Date:</strong> <%= @booking.end_date %></p>
        <p><strong>Total Days:</strong> <%= @booking.total_days %></p>
        <p><strong>Daily Price:</strong> <%= number_to_currency(@booking.instrument.price) %></p>
        <p><strong>Total Price:</strong> <%= number_to_currency(@booking.total_price) %></p>
        <%= link_to 'Edit Booking', edit_booking_path(@booking), class: 'bouton' %>
        <%= link_to 'Back', request.referrer || bookings_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
  <div class="container mt-5">
    <div class="col-md-6 mb-5">
        <% if @booking.instrument.photos.attached? %>
          <div id="carousel-<%= @booking.instrument.id %>" class="carousel slide w-100" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <% @booking.instrument.photos.each_with_index do |photo, index| %>
                <button type="button" data-bs-target="#carousel-<%= @booking.instrument.id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>" aria-current="<%= 'true' if index == 0 %>" aria-label="Slide <%= index + 1 %>"></button>
              <% end %>
            </div>
            <div class="carousel-inner">
              <% @booking.instrument.photos.each_with_index do |photo, index| %>
                <div class="carousel-item <%= 'active' if index == 0 %>">
                  <%= image_tag url_for(photo), class: "d-block w-100", id: "instrument-photo" %>
                </div>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= @booking.instrument.id %>" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= @booking.instrument.id %>" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <% else %>
          <p>No photos available for this instrument.</p>
          <% end %>
          <div>
        </div>
    </div>
  </div>
</div>

app/views/instruments/_info_window.html.erb
<h2><%= instrument.title %></h2>
<p><%= instrument.location %></p>

app/views/instruments/_marker.html.erb
<%= image_tag "arrow.png", height: 50, width: 50, alt: "Arrow" %>

app/views/instruments/edit.html.erb
<div class="container mt-5">
  <h1>Edit Instrument</h1>
  <div class="mt-2">
      <%= simple_form_for @instrument do |f| %>
        <%= f.input :title %>
        <%= f.input :body %>
        <%= f.input :price,  as: :numeric, input_html: { min: 0 }  %>
        <%= f.input :category, collection: ["String", "Percussion", "Wind", "Keyboard", "Electronic"] %>
        <%= f.input :start_date, as: :string, input_html: { id: 'start_date' } %>
        <%= f.input :end_date, as: :string, input_html: { id: 'end_date' } %>
        <%= f.input :availability, collection: ["Yes", "No"] %>
        <%= f.input :location %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit %>
      <% end %>
    </div>
        <%= link_to 'Back', instrument_path(@instrument), class: "btn btn-secondary" %>
        <%= link_to 'Delete', instrument_path(@instrument),data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
</div>

app/views/instruments/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1554446422-c4d46271ab85?q=80&w=2074&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="row">
    <div class="col-12">
      <h1>RENT 'N PLAY</h1>
      <h2>Unleash Your Musical Journey : Rent, Play, Repeat !</h2>
    </div>
    <div class="col-6 mt-5">
          <%= form_with url: instruments_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control rounder-lg me-2 border form-control-lg",
                  placeholder: "Type a keyword"
              %>
            <%= submit_tag "Search", name: "", class: "btn btn-info btn-lg" %>
          <% end %>
    </div>
  </div>
</div>


<div class="container mt-5">
  <div class="row row-cols-3 gy-2">
    <% @instruments.each do |instrument| %>
      <div class="col col-md-6 col-lg-4 col-xl-3 mb-4 col-sm-12 col-xs-12">
        <div class="card border border-warning rounded-5 border-1" id="index-card">
                      <% if instrument.photos.attached? %>
                <div id="carousel-<%= instrument.id %>" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-indicators">
                    <% instrument.photos.each_with_index do |photo, index| %>
                      <button type="button" data-bs-target="#carousel-<%= instrument.id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>" aria-current="<%= 'true' if index == 0 %>" aria-label="Slide <%= index + 1 %>"></button>
                    <% end %>
                  </div>
                  <div class="carousel-inner">
                    <% instrument.photos.each_with_index do |photo, index| %>
                      <div class="carousel-item <%= 'active' if index == 0 %>">
                        <%= image_tag url_for(photo), class: "d-block w-100", id: "image-index" %>
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= instrument.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= instrument.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
              <% else %>
                <p>No photos available for this instrument.</p>
              <% end %>

          <div class="card-body">
            <h5 class="card-title"><%= instrument.title %></h5>
            <p><strong>Category</strong>: <%= instrument.category %></p>
            <p><strong>Location</strong>: <%= instrument.location %></p>
            <p><strong>Availability</strong>: From <%= instrument.start_date %> to <%= instrument.end_date %></p>
            <p><strong>Price</strong>: <%= instrument.price %> <i class="fa-solid fa-euro-sign"></i></p>
            <p><strong>Owner</strong>: <%= instrument.user.first_name %> <%= instrument.user.last_name %></p>
                <p><strong>Available ?</strong> <%=instrument.availability%>
              <% if instrument.availability == "Yes" %>
               <i class="fa-solid fa-check"></i>
              <% else %>
             <i class="fa-solid fa-times"></i>
              <% end %>
              </p>

            <%= link_to 'Show Instrument', instrument_path(instrument), class:"btn custom-submit-button btn-border-lg" %>

            <%# <%= link_to 'Edit', edit_instrument_path(instrument), class:"btn btn-info" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/instruments/new.html.erb
<h1>Add your Instrument</h1>
  <div class="mt-2">
    <%= simple_form_for @instrument, html: { data: { controller: :datepicker } } do |f| %>
      <%= f.input :title %>
      <%= f.input :body %>
      <%= f.input :price,  as: :numeric, input_html: { min: 0 } %>
      <%= f.input :location %>
      <%= f.input :category, collection: ["String", "Percussion", "Wind", "Keyboard", "Electronic"]%>
      <%= f.input :start_date, as: :string, input_html: { data: { datepicker_target: "startDate" } , id: 'start_date' } %>
      <%= f.input :end_date, as: :string, input_html: { data: { datepicker_target: "endDate" }, id: 'end_date' } %>
      <%= f.input :availability, collection: ["Yes", "No"] %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, 'Submit', class: 'custom-submit-button' %>
    <% end %>
  </div>

  <%= link_to 'Back', instruments_path, class: "btn btn-secondary" %>

app/views/instruments/show.html.erb
<div class="row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title"><%= @instrument.title %></h1>
        <p><strong>Posted by:</strong> <%= @instrument.user.first_name %> <%= @instrument.user.last_name %></p>
          <p><strong>Category:</strong> <%= @instrument.category %></p>
              <p><strong>Price per day:</strong> <%= @instrument.price %> <i class="fa-solid fa-euro-sign"></i></p>
              <p><strong>Description:</strong></p>
              <p><%= @instrument.body %></p>
              <p><strong>Location:</strong> <%= @instrument.location %></p>
              <p><strong>Available ?</strong> <%=@instrument.availability%>
              <% if @instrument.availability == "Yes" %>
                <i class="fa-solid fa-check"></i>
                <p class="mt-4"><strong>Available:</strong> From <%= @instrument.start_date %> to <%= @instrument.end_date %></p>
              <% else %>
                <i class="fa-solid fa-times"></i>
              <% end %>
          </p>
          <div style="width: 100%; height: 400px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-apikey-value="<%= ENV['MAPBOX_API_KEY'] %>">
             map.scrollZoom.disable();
          </div>
          <div class="mt-5">
            <% if @instrument.user == current_user %>
            <%= link_to 'Edit', edit_instrument_path(@instrument), class: "btn btn-primary" %>
            <% elsif @instrument.availability == "Yes" %>
            <%= link_to 'Rent', new_instrument_booking_path(@instrument), class: "btn btn-primary" %>
            <% end %>
            <% if @instrument.user == current_user %>
            <%= link_to 'Delete', instrument_path(@instrument), data: {"turbo-method": :delete, confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
            <%= link_to 'Back', instruments_path, class: "btn btn-secondary" %>
          </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <div>
               <% if @instrument.photos.attached? %>
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-indicators">
                    <% @instrument.photos.each_with_index do |photo, index| %>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>" aria-current="<%= 'true' if index == 0 %>" aria-label="Slide <%= index + 1 %>"></button>
                    <% end %>
                  </div>
                  <div class="carousel-inner">
                    <% @instrument.photos.each_with_index do |photo, index| %>
                      <div class="carousel-item <%= 'active' if index == 0 %>">
                        <%= image_tag photo, class: "d-block w-100" %>
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
              <% else %>
                <p>No photos available for this instrument.</p>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentNPlay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="sticky">
        <div class="container-fluid mx-5">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "logo-rent-n-play.png" %>
          <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto my-auto">
              <% if user_signed_in? %>
                  <% if current_page?(root_path) %>
                    <% else %>
                      <li class="nav-item active">
                        <%= link_to "Home", root_path, class: "nav-link" %>
                      </li>
                  <% end %>
                <li class="nav-item active">
                  <%= link_to "My bookings", bookings_path, class: "nav-link" %>
                </li>
                <li class="nav-item active">
                  <%= link_to "My instruments", user_instruments_path, class: "nav-link" %>
                </li>
                <li class="nav-item active">
                <%= link_to "Add an Instrument", new_instrument_path, class: "nav-link mr-5" %>
                </li>
                <li class="nav-item dropdown">
                  <% if current_user.photo.attached? %>
                    <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% else %>
                    <%= image_tag "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "Profil", edit_user_registration_path, class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", style: "color:red;", data: {turbo_method: :delete} %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <div class="container mt-5">
      <%= yield %>
    </div>

    <div>
      <div class="footer">
        <div class="footer-links align-center">

          <a href="https://github.com/davidgomescarvalho/rent-n-play"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>index of all the instruments</h1>